name: Gunpvp
author: Bernhard Scharrer
version: 1.0
main: gunpvp.Gunpvp

commands:
  spawn:
    description:
    aliases: [s,main,lobby,l,hub]
  info:
    description:
    aliases: [i]
  shop:
    description:
    aliases: [buy]
  ping:
    description:
    aliases: [p]
  enderchest:
    description:
    aliases: [ec]