name: Gunpvp
author: Bernhard Scharrer, Thomas Langs
version: 2.1
main: gunpvp.Gunpvp

commands:
  spawn:
    description:
    aliases: [s,main,lobby,l,hub]
  info:
    description:
    aliases: [i]
  shop:
    description:
    aliases: [buy]
  ping:
    description:
    aliases: [p]
  enderchest:
    description:
    aliases: [ec]
  database:
    description:
    aliases: [db]
  stats:
    description:
  money:
    aliases: [m,cash]